name: ml
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - pytorch
  - torchvision
  - pip
  - pip:
    - pytorch-lightning
